# Generated by Django 5.2.3 on 2025-06-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_pin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
