# Generated by Django 5.2.3 on 2025-06-23 16:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reset_password_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=users.models.GenerateProfileImagePath),
        ),
    ]
