# Generated by Django 5.2.3 on 2025-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_city_user_country_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Farmer', 'Farmer'), ('Agronomist', 'Agronomist')], max_length=20, null=True),
        ),
    ]
